// Basic 6, Advanced 3, Elite 1

// special are top 5%

export const pedigree = {
	// Basic
	commonLevelOne: [
		'Recruit',
		'Apprentice',
		'Private',
		'Corporal',
		'Sergeant',
		'Gunnery Sergeant',
		'Lieutenant',
		'Captain',
	],
	specialLevelOne: ['Master Sergeant', 'First Lieutenant', 'Staff Captain'],
	// Advanced
	commonLevelTwo: ['Major', 'Commander', 'Colonel', 'Brigadier'],
	specialLevelTwo: [
		'Field Major',
		'Strike Commander',
		'Force Colonel',
		'Brigadier General'
	],
	//Elite
	commonLevelThree: ['General'],
	specialLevelThree: [
		'5-Star General'
	],
};

export const faang = {
	basic: {
		dra: {
			rank: 'Basic',
			type: 'Dra',
			health: 41,
			attack: 89,
			defense: 47.5,
			regeneration: 18.5,
			speed: 50,
			total: 246,
		},
		tyr: {
			rank: 'Basic',
			type: 'Tyr',
			health: 50,
			attack: 54.5,
			defense: 50,
			regeneration: 24.25,
			speed: 41,
			total: null,
		},
		sal: {
			rank: 'Basic',
			type: 'Sal',
			health: 45,
			attack: 57.5,
			defense: 45,
			regeneration: 18.5,
			speed: 50,
			total: null,
		},
		met: {
			rank: 'Basic',
			type: 'Met',
			health: 40,
			attack: 40,
			defense: 70,
			regeneration: 16.25,
			speed: 30,
			total: null,
		},
		gar: {
			rank: 'Basic',
			type: 'Gar',
			health: 58,
			attack: 55,
			defense: 45,
			regeneration: 21.5,
			speed: 42,
			total: null,
		},
		hyd: {
			rank: 'Basic',
			type: 'Hyd',
			health: 52,
			attack: 55,
			defense: 50,
			regeneration: 21,
			speed: 38,
			total: null,
		},
		goo: {
			rank: 'Basic',
			type: 'Goo',
			health: 45,
			attack: 52.5,
			defense: 55,
			regeneration: 18.5,
			speed: 40,
			total: null,
		},
		kom: {
			rank: 'Basic',
			type: 'Kom',
			health: 45,
			attack: 50,
			defense: 55,
			regeneration: 18.5,
			speed: 45,
			total: null,
		},
		pul: {
			rank: 'Basic',
			type: 'Pul',
			health: 28,
			attack: 50,
			defense: 30,
			regeneration: 18,
			speed: 82,
			total: null,
		},
	},
	advanced: {
		dra: {
			rank: 'Advanced',
			type: 'Dra',
			health: 61,
			attack: 77,
			defense: 67.5,
			regeneration: 18.5,
			speed: 70,
			total: null,
		},
		tyr: {
			rank: 'Advanced',
			type: 'Tyr',
			health: 70,
			attack: 74.5,
			defense: 70,
			regeneration: 24.25,
			speed: 51,
			total: null,
		},
		sal: {
			rank: 'Advanced',
			type: 'Sal',
			health: 65,
			attack: 77.5,
			defense: 75,
			regeneration: 18.5,
			speed: 50,
			total: null,
		},
		met: {
			rank: 'Advanced',
			type: 'Met',
			health: 60,
			attack: 65,
			defense: 90,
			regeneration: 16.25,
			speed: 50,
			total: null,
		},
		gar: {
			rank: 'Advanced',
			type: 'Gar',
			health: 68,
			attack: 70,
			defense: 60,
			regeneration: 21.5,
			speed: 82,
			total: null,
		},
		hyd: {
			rank: 'Advanced',
			type: 'Hyd',
			health: 72,
			attack: 75,
			defense: 70,
			regeneration: 21,
			speed: 58,
			total: null,
		},
		goo: {
			rank: 'Advanced',
			type: 'Goo',
			health: 68,
			attack: 79,
			defense: 83,
			regeneration: 18.5,
			speed: 60,
			total: null,
		},
		kom: {
			rank: 'Advanced',
			type: 'Kom',
			health: 55,
			attack: 70,
			defense: 80,
			regeneration: 22,
			speed: 65,
			total: null,
		},
		pul: {
			rank: 'Advanced',
			type: 'Pul',
			health: 68,
			attack: 70,
			defense: 50,
			regeneration: 18,
			speed: 102,
			total: null,
		},
	},
	elite: {
		dra: {
			rank: 'Elite',
			type: 'Dra',
			health: 91,
			attack: 117,
			defense: 97.5,
			regeneration: 20.25,
			speed: 80,
			total: null,
		},
		tyr: {
			rank: 'Elite',
			type: 'Tyr',
			health: 100,
			attack: 129.5,
			defense: 135,
			regeneration: 23,
			speed: 71,
			total: null,
		},
		sal: {
			rank: 'Elite',
			type: 'Sal',
			health: 95,
			attack: 122.5,
			defense: 80,
			regeneration: 20.25,
			speed: 100,
			total: null,
		},
		met: {
			rank: 'Elite',
			type: 'Met',
			health: 80,
			attack: 115,
			defense: 110,
			regeneration: 16.25,
			speed: 70,
			total: null,
		},
		gar: {
			rank: 'Elite',
			type: 'Gar',
			health: 108,
			attack: 105,
			defense: 90,
			regeneration: 21.5,
			speed: 102,
			total: null,
		},
		hyd: {
			rank: 'Elite',
			type: 'Hyd',
			health: 92,
			attack: 115,
			defense: 90,
			regeneration: 21,
			speed: 98,
			total: null,
		},
		goo: {
			rank: 'Elite',
			type: 'Goo',
			health: 90,
			attack: 105,
			defense: 110,
			regeneration: 18.5,
			speed: 80,
			total: null,
		},
		kom: {
			rank: 'Elite',
			type: 'Kom',
			health: 75,
			attack: 105,
			defense: 115,
			regeneration: 22,
			speed: 85,
			total: null,
		},
		pul: {
			rank: 'Elite',
			type: 'Pul',
			health: 88,
			attack: 110,
			defense: 75,
			regeneration: 18,
			speed: 142,
			total: null,
		},
	},
};
