// basic 6, advanced 3, elite 1

export const ranks = ['Recruit', 'Apprentice', 'Private', 'Corporal', 'Sergeant', 'Gunnery Sergeant', 'Lieutenant', 'Captain', 'Major', 'Commander', 'Colonel', 'Brigadier', 'General',];
export const specialRanks = ['Master Sergeant', 'First Lieutenant', 'Staff captain', 'Field major', 'Strike commander', 'Force colonel', 'Brigadier General', '5-Star General'];

export const faang = {
	basic: {
		dra: {
			rank: 'basic',
			type: 'dra',
			health: 41,
			attack: 89,
			defense: 47.5,
			regeneration: 18.5,
			speed: 50,
			total: 246,
		},
		tyr: {
			rank: 'basic',
			type: 'tyr',
			health: 50,
			attack: 54.5,
			defense: 50,
			regeneration: 24.25,
			speed: 41,
			total: null,
		},
		sal: {
			rank: 'basic',
			type: 'sal',
			health: 45,
			attack: 57.5,
			defense: 45,
			regeneration: 18.5,
			speed: 50,
			total: null,
		},
		met: {
			rank: 'basic',
			type: 'met',
			health: 40,
			attack: 40,
			defense: 70,
			regeneration: 16.25,
			speed: 30,
			total: null,
		},
		gar: {
			rank: 'basic',
			type: 'gar',
			health: 58,
			attack: 55,
			defense: 45,
			regeneration: 21.5,
			speed: 42,
			total: null,
		},
		hyd: {
			rank: 'basic',
			type: 'hyd',
			health: 52,
			attack: 55,
			defense: 50,
			regeneration: 21,
			speed: 38,
			total: null,
		},
		goo: {
			rank: 'basic',
			type: 'goo',
			health: 45,
			attack: 52.5,
			defense: 55,
			regeneration: 18.5,
			speed: 40,
			total: null,
		},
		kom: {
			rank: 'basic',
			type: 'kom',
			health: 45,
			attack: 50,
			defense: 55,
			regeneration: 18.5,
			speed: 45,
			total: null,
		},
		pul: {
			rank: 'basic',
			type: 'pul',
			health: 28,
			attack: 50,
			defense: 30,
			regeneration: 18,
			speed: 82,
			total: null,
		},
	},
	advanced: {
		dra: {
			rank: 'advanced',
			type: 'dra',
			health: 61,
			attack: 77,
			defense: 67.5,
			regeneration: 18.5,
			speed: 70,
			total: null,
		},
		tyr: {
			rank: 'advanced',
			type: 'tyr',
			health: 70,
			attack: 74.5,
			defense: 70,
			regeneration: 24.25,
			speed: 51,
			total: null,
		},
		sal: {
			rank: 'advanced',
			type: 'sal',
			health: 65,
			attack: 77.5,
			defense: 75,
			regeneration: 18.5,
			speed: 50,
			total: null,
		},
		met: {
			rank: 'advanced',
			type: 'met',
			health: 60,
			attack: 65,
			defense: 90,
			regeneration: 16.25,
			speed: 50,
			total: null,
		},
		gar: {
			rank: 'advanced',
			type: 'gar',
			health: 68,
			attack: 70,
			defense: 60,
			regeneration: 21.5,
			speed: 82,
			total: null,
		},
		hyd: {
			rank: 'advanced',
			type: 'hyd',
			health: 72,
			attack: 75,
			defense: 70,
			regeneration: 21,
			speed: 58,
			total: null,
		},
		goo: {
			rank: 'advanced',
			type: 'goo',
			health: 68,
			attack: 79,
			defense: 83,
			regeneration: 18.5,
			speed: 60,
			total: null,
		},
		kom: {
			rank: 'advanced',
			type: 'kom',
			health: 55,
			attack: 70,
			defense: 80,
			regeneration: 22,
			speed: 65,
			total: null,
		},
		pul: {
			rank: 'advanced',
			type: 'pul',
			health: 68,
			attack: 70,
			defense: 50,
			regeneration: 18,
			speed: 102,
			total: null,
		},
	},
	elite: {
		dra: {
			rank: 'elite',
			type: 'dra',
			health: 91,
			attack: 117,
			defense: 97.5,
			regeneration: 20.25,
			speed: 80,
			total: null,
		},
		tyr: {
			rank: 'elite',
			type: 'tyr',
			health: 100,
			attack: 129.5,
			defense: 135,
			regeneration: 23,
			speed: 71,
			total: null,
		},
		sal: {
			rank: 'elite',
			type: 'sal',
			health: 95,
			attack: 122.5,
			defense: 80,
			regeneration: 20.25,
			speed: 100,
			total: null,
		},
		met: {
			rank: 'elite',
			type: 'met',
			health: 80,
			attack: 115,
			defense: 110,
			regeneration: 16.25,
			speed: 70,
			total: null,
		},
		gar: {
			rank: 'elite',
			type: 'gar',
			health: 108,
			attack: 105,
			defense: 90,
			regeneration: 21.5,
			speed: 102,
			total: null,
		},
		hyd: {
			rank: 'elite',
			type: 'hyd',
			health: 92,
			attack: 115,
			defense: 90,
			regeneration: 21,
			speed: 98,
			total: null,
		},
		goo: {
			rank: 'elite',
			type: 'goo',
			health: 90,
			attack: 105,
			defense: 110,
			regeneration: 18.5,
			speed: 80,
			total: null,
		},
		kom: {
			rank: 'elite',
			type: 'kom',
			health: 75,
			attack: 105,
			defense: 115,
			regeneration: 22,
			speed: 85,
			total: null,
		},
		pul: {
			rank: 'elite',
			type: 'pul',
			health: 88,
			attack: 110,
			defense: 75,
			regeneration: 18,
			speed: 142,
			total: null,
		},
	},
};
